### ISSUE TITLE
建议 支持macOS安装

### ISSUE THREAD

**Issue by lunzima** [love4taylor/pve-edk2-firmware#1]
使用这个commit补丁，看起来使用新版本edk2可以正常patch
https://github.com/thenickdude/edk2/commit/1312511bf2ec3b61f63eefb936c0cf84ac820697

**Comment by love4taylor** [comment]
单这一个 patch 就行了？

**Comment by love4taylor** [comment]
你可以试试，我这服务器资源快满了腾不出来装 macOS。

[pve-edk2-firmware_3.20210918-1_all.deb](https://github.com/love4taylor/pve-edk2-firmware/releases/download/3.20210918-1/pve-edk2-firmware_3.20210918-1_all.deb)

**Comment by lunzima** [comment]
问题解决了，感谢

**Comment by lunzima** [comment]
上面的链接似乎损坏了，能否直接传到release？

**Comment by love4taylor** [comment]
我的锅，忘打 tag 存成 draft 了，已更新。
